"use client";
import { useState } from "react";
const exports=["participants","trials","guided_responses","gift_candidates","product_catalog","final_selections","event_logs","experiment_metadata","analysis_ready","behavior_analysis_ready"];
export default function AdminPage(){
  const [password,setPassword]=useState("");const [summary,setSummary]=useState<any>(null);const [error,setError]=useState("");const [dataMode,setDataMode]=useState("all");
  async function load(){const r=await fetch("/api/admin/summary",{headers:{"x-admin-password":password}});const d=await r.json();if(!r.ok){setError(d.error);return;}sessionStorage.setItem("adminPassword",password);setSummary(d);setError("");}
  async function download(name:string){const r=await fetch(`/api/admin/export?name=${name}`,{headers:{"x-admin-password":password}});if(!r.ok){setError("CSV 내보내기에 실패했습니다.");return;}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${name}.csv`;a.click();URL.revokeObjectURL(url);}
  const metrics:any={전체:summary?.total,High:summary?.high,Low:summary?.low,Giver:summary?.giver,Recipient:summary?.recipient,완료:summary?.completed,진행중:summary?.active,미완료:summary?.incomplete,훈련오답:summary?.trainingFailures,Mock:summary?.mock,Real:summary?.real,Trial완료율:`${summary?.trialCompletionRate}%`};
  return <main className="shell"><section className="panel"><p className="eyebrow">연구자 관리</p><h1 className="title">관리자 대시보드</h1><label>관리자 비밀번호<input className="field" type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button className="button" onClick={load}>현황 불러오기</button>{error&&<p role="alert">{error}</p>}{summary&&<><div className="grid" style={{marginTop:22}}>{Object.entries(metrics).map(([k,v])=><div className="card" key={k}><p className="eyebrow">{k}</p><h2>{String(v)}</h2></div>)}</div><h2 style={{marginTop:24}}>배정·노출 현황</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify({sequences:summary.sequence,conditions:summary.conditionExposure,profiles:summary.profileExposure},null,2)}</pre><h2>참가자</h2><select className="field" value={dataMode} onChange={e=>setDataMode(e.target.value)}><option value="all">Mock + Real</option><option value="real">Real only</option><option value="mock">Mock only</option></select><div className="grid">{summary.participants.filter((p:any)=>dataMode==="all"||(dataMode==="mock"?p.isMock:!p.isMock)).map((p:any)=><a className="card" href={`/admin/participants/${p.id}`} key={p.id}><b>{p.code}</b><p className="eyebrow">{p.isMock?"MOCK DATA":"REAL DATA"} · {p.role} · {p.status}</p></a>)}</div><h2 style={{marginTop:24}}>데이터 내보내기</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{exports.map(x=><button key={x} className="button secondary" onClick={()=>download(x)}>{x}.csv</button>)}</div><p className="eyebrow" style={{marginTop:20}}>Mock: {summary.mock} · Real: {summary.real}</p></>}</section></main>;
}
