import { supabaseAdmin } from "@/lib/supabase/server";
import { EXPERIMENT } from "@/config/experiment";

export async function logEvent(input: { participantId: string; trialId?: string; eventType: string; payload?: Record<string, unknown>; elapsedMs?: number; elapsedFromTrialStartMs?:number; effectiveExposureMs?:number; eventTarget?:string; eventValue?:string; clientTimestamp?:string; phase?:string; actorType?:"participant"|"agent"|"system"|"simulated_giver"; taskId?:string; messageId?:string; simulatedActorEvent?:boolean; idempotencyKey?:string; eventOrigin?:"participant"|"recorded"|"scripted"|"system"; transcriptId?:string; stimulusVersion?:number; inputMode?:"chat"|"dropdown"; intent?:string }) {
  const db = supabaseAdmin();
  const { data: p } = await db.from("participants").select("participant_code,role,intimacy_condition,sequence_id,is_mock").eq("id", input.participantId).single();
  const { data: t } = input.trialId ? await db.from("trials").select("trial_number,profile_id,condition_id,execution_autonomy,decision_authority,current_phase,started_at,stimulus_id,stimulus_version,stimulus_source").eq("id", input.trialId).single() : { data: null };
  const serverTimestamp=new Date().toISOString();
  const elapsedFromStart=input.elapsedFromTrialStartMs??(t?.started_at?Math.max(0,Date.now()-new Date(t.started_at).getTime()):null);
  const stimulusOrigin=t?.stimulus_source==="recorded"?"recorded":"scripted";
  const origin=input.eventOrigin??(input.actorType==="simulated_giver"?stimulusOrigin:input.actorType==="agent"?(p?.role==="recipient"?stimulusOrigin:"system"):input.actorType==="system"?"system":"participant");
  const { error } = await db.from("event_logs").insert({ participant_id: input.participantId, participant_code:p?.participant_code??null, trial_id: input.trialId ?? null, event_type: input.eventType, event_target:input.eventTarget??null,event_value:input.eventValue??null,payload: input.payload ?? {},payload_json:input.payload??{}, elapsed_ms: input.elapsedMs ?? null,elapsed_from_trial_start_ms:elapsedFromStart,effective_exposure_ms:input.effectiveExposureMs??null,client_timestamp:input.clientTimestamp??null,server_timestamp:serverTimestamp,created_at:serverTimestamp,experiment_version: EXPERIMENT.version, role: p?.role, intimacy_condition: p?.intimacy_condition, sequence_id: p?.sequence_id, is_mock: p?.is_mock ?? false, trial_number: t?.trial_number, profile_id: t?.profile_id, condition_id: t?.condition_id,execution_autonomy:t?.execution_autonomy,decision_authority:t?.decision_authority,phase:input.phase??t?.current_phase??null,actor_type:input.actorType??"participant",task_id:input.taskId??null,message_id:input.messageId??null,simulated_actor_event:input.simulatedActorEvent??input.actorType==="simulated_giver",idempotency_key:input.idempotencyKey??null,event_origin:origin,transcript_id:input.transcriptId??t?.stimulus_id??null,stimulus_version:input.stimulusVersion??t?.stimulus_version??null,input_mode:input.inputMode??null,intent:input.intent??null });
  if (error && !(input.idempotencyKey && error.code === "23505")) throw error;
}
