import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/server";
import { deriveBehaviorMetrics } from "@/lib/experiment/behavior";
const allowed=["participants","trials","guided_responses","gift_candidates","product_catalog","final_selections","event_logs","experiment_metadata","analysis_ready","behavior_analysis_ready"];
const csv=(rows:any[],columns:string[])=>[columns.join(","),...rows.map(r=>columns.map(c=>{const value=r[c];const text=typeof value==="string"?value:JSON.stringify(value??"");return `"${text.replaceAll('"','""')}"`;}).join(","))].join("\n");
export async function GET(req:Request){if(!process.env.ADMIN_PASSWORD||req.headers.get("x-admin-password")!==process.env.ADMIN_PASSWORD)return NextResponse.json({error:"관리자 인증이 필요합니다."},{status:401});const name=new URL(req.url).searchParams.get("name")??"";if(!allowed.includes(name))return NextResponse.json({error:"지원하지 않는 CSV입니다."},{status:400});try{const db=supabaseAdmin();let rows:any[]=[],columns:string[]=[];
 if(name==="analysis_ready"){const {data,error}=await db.from("trials").select("id,participant_id,trial_number,profile_id,condition_id,execution_autonomy,decision_authority,started_at,completed_at,is_mock,participants(participant_code,role,intimacy_condition,sequence_id,training_attempts,experiment_version),recipient_profiles(profile_code),final_selections(selected_by,selected_candidate_id),trial_candidates(gift_candidate_id,gift_candidates(product_name))").order("participant_id").order("trial_number");if(error)throw error;rows=(data??[]).map((t:any)=>{const selection=Array.isArray(t.final_selections)?t.final_selections[0]:t.final_selections;const picked=t.trial_candidates?.find((c:any)=>c.gift_candidate_id===selection?.selected_candidate_id);return {participant_id:t.participants?.participant_code,role:t.participants?.role,intimacy:t.participants?.intimacy_condition,sequence:t.participants?.sequence_id,trial_number:t.trial_number,recipient_profile:t.recipient_profiles?.profile_code,condition:t.condition_id,execution_autonomy:t.execution_autonomy,decision_authority:t.decision_authority,selected_candidate:picked?.gift_candidates?.product_name??"",selected_by:selection?.selected_by??"",trial_duration_ms:t.started_at&&t.completed_at?new Date(t.completed_at).getTime()-new Date(t.started_at).getTime():"",training_attempts:t.participants?.training_attempts,experiment_version:t.participants?.experiment_version,is_mock:t.is_mock};});columns=Object.keys(rows[0]??{participant_id:"",trial_number:"",is_mock:""});}
 else if(name==="behavior_analysis_ready"){const {data,error}=await db.from("trials").select("id,participant_id,trial_number,profile_id,condition_id,execution_autonomy,decision_authority,status,experiment_version,is_mock,participants(participant_code,role,intimacy_condition,sequence_id),recipient_profiles(profile_code),guided_responses(response_time_ms,revision_count,confirmed_at,shown_at,answered_at),event_logs(event_type,event_target,event_value,client_timestamp,server_timestamp,created_at,elapsed_ms,payload,payload_json)").order("participant_id").order("trial_number");if(error)throw error;rows=(data??[]).map((trial:any)=>{const events=trial.event_logs??[];const responses=trial.guided_responses??[];const metrics=deriveBehaviorMetrics(events,responses,trial.decision_authority,trial.execution_autonomy==="human_guided",trial.status==="completed");return {participant_id:trial.participants?.participant_code,trial_number:trial.trial_number,role:trial.participants?.role,intimacy:trial.participants?.intimacy_condition,sequence:trial.participants?.sequence_id,profile:trial.recipient_profiles?.profile_code,condition:trial.condition_id,execution_autonomy:trial.execution_autonomy,decision_authority:trial.decision_authority,...metrics,experiment_version:trial.experiment_version,is_mock:trial.is_mock};});columns=Object.keys(rows[0]??{participant_id:"",trial_number:"",total_task_time_ms:"",is_mock:""});}
 else if(name==="experiment_metadata"){rows=[{experiment_version:"1.0.0",ui_version:"1.0.0",profile_version:"profiles-v1",candidate_version:"candidates-v1",prompt_version:"gift-prompt-v1",sequence_version:"williams-v1",candidate_mode:process.env.EXPERIMENT_CANDIDATE_MODE??"controlled"}];columns=Object.keys(rows[0]);}
 else {const {data,error}=await db.from(name).select("*").limit(10000);if(error)throw error;rows=data??[];columns=Object.keys(rows[0]??{});}
 return new NextResponse("\ufeff"+csv(rows,columns),{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="${name}.csv"`}});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"CSV 내보내기 실패"},{status:500});}}
